spring:
  config:
    activate:
      on-profile: dev
  application:
    name: BLSDemo

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bls_data
    username: postgres
    password: password
    initializion-mode: true


logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            security: DEBUG
    com:
      fshtank:
        bls: DEBUG
    web: DEBUG


